"""remove user telegram_id

Revision ID: ef1428ae73a1
Revises: 007250d686e1
Create Date: 2023-02-04 16:55:28.719756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1428ae73a1'
down_revision = '007250d686e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
